import os
import json
from dotenv import load_dotenv
import google.generativeai as genai


load_dotenv()


class ReviewerAgent:
    """
    Evaluates the response generated by a specialized agent
    and decides whether it is good enough or needs revision.
    """

    def __init__(self):
        api_key = os.getenv("GEMINI_API_KEY")

        if not api_key:
            raise ValueError(
                "GEMINI_API_KEY not found in .env file."
            )

        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel("gemini-3.5-flash")


    def review(self, user_prompt, task, response):
        """
        Review an agent's response and return a structured result.
        """

        review_prompt = f"""
You are the Reviewer Agent for Creatix,
an autonomous coding assistant.

Your job is to evaluate the response generated by another AI agent.

Original user request:
{user_prompt}

Selected task:
{task}

Agent response:
{response}

Evaluate the response based on:

1. Correctness
2. Relevance to the user's request
3. Technical accuracy
4. Completeness
5. Clarity
6. Whether the code is likely to work

Return ONLY valid JSON in exactly this format:

{{
    "approved": true,
    "score": 8,
    "feedback": "Brief explanation of the review",
    "revision_instructions": ""
}}

Rules:

- "approved" must be true or false.
- "score" must be an integer from 1 to 10.
- Approve responses with a score of 7 or higher.
- If approved, revision_instructions should be empty.
- If not approved, provide specific revision instructions.
"""

        gemini_response = self.model.generate_content(review_prompt)
        response_text = gemini_response.text.strip()

        # Remove Markdown code fences if Gemini adds them
        if response_text.startswith("```"):
            response_text = (
                response_text
                .replace("```json", "")
                .replace("```", "")
                .strip()
            )

        try:
            review = json.loads(response_text)

        except json.JSONDecodeError:
            raise ValueError(
                f"Reviewer returned invalid JSON: {response_text}"
            )

        # Validate returned data
        required_fields = [
            "approved",
            "score",
            "feedback",
            "revision_instructions",
        ]

        for field in required_fields:
            if field not in review:
                raise ValueError(
                    f"Reviewer response missing field: {field}"
                )

        if not isinstance(review["approved"], bool):
            raise ValueError(
                "Reviewer field 'approved' must be boolean."
            )

        if not isinstance(review["score"], int):
            raise ValueError(
                "Reviewer field 'score' must be an integer."
            )

        if not 1 <= review["score"] <= 10:
            raise ValueError(
                "Reviewer score must be between 1 and 10."
            )

        return review
    
    def _revise_response(
        self,
        user_prompt,
        task,
        original_response,
        revision_instructions,
        conversation_context=None,
    ):
        """
        Revise an agent response using the reviewer's instructions.
        """

        revision_prompt = f"""
            You are the Revision Agent for Creatix,
            an autonomous coding assistant.

            Your job is to improve an AI-generated response based on
            specific reviewer feedback.

            Original user request:
            {user_prompt}

            Selected task:
            {task}

            Original agent response:
            {original_response}

            Revision instructions:
            {revision_instructions}

            Conversation context:
            {conversation_context or "No additional conversation context provided."}

            Generate an improved final response that:

            1. Fixes all issues identified by the reviewer.
            2. Fully addresses the user's original request.
            3. Is technically accurate.
            4. Is clear and complete.
            5. Preserves correct parts of the original response.

            Return ONLY the improved response.
            """

        gemini_response = self.model.generate_content(
            revision_prompt
        )

        return gemini_response.text.strip()
    
    def review_and_revise(
        self,
        user_prompt,
        task,
        original_response,
        conversation_context=None,
    ):
        """
        Review the original response and revise it if necessary.
        """

        review = self.review(
            user_prompt=user_prompt,
            task=task,
            response=original_response,
        )

        if review["approved"]:
            final_response = original_response

        else:
            final_response = self._revise_response(
                user_prompt=user_prompt,
                task=task,
                original_response=original_response,
                revision_instructions=review[
                    "revision_instructions"
                ],
                conversation_context=conversation_context,
            )

        return {
            "original_response": original_response,
            "review": review,
            "final_response": final_response,
        }