import os
import json
from dotenv import load_dotenv
import google.generativeai as genai


load_dotenv()


class ReviewerAgent:
    """
    Evaluates the response generated by a specialized agent
    and decides whether it is good enough or needs revision.
    """

    def __init__(self):
        api_key = os.getenv("GEMINI_API_KEY")

        if not api_key:
            raise ValueError(
                "GEMINI_API_KEY not found in .env file."
            )

        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel("gemini-3.5-flash")


    def review(self, user_prompt, task, response):
        """
        Review an agent's response and return a structured result.
        """

        review_prompt = f"""
You are the Reviewer Agent for Creatix,
an autonomous coding assistant.

Your job is to evaluate the response generated by another AI agent.

Original user request:
{user_prompt}

Selected task:
{task}

Agent response:
{response}

Evaluate the response based on:

1. Correctness
2. Relevance to the user's request
3. Technical accuracy
4. Completeness
5. Clarity
6. Whether the code is likely to work

Return ONLY valid JSON in exactly this format:

{{
    "approved": true,
    "score": 8,
    "feedback": "Brief explanation of the review",
    "revision_instructions": ""
}}

Rules:

- "approved" must be true or false.
- "score" must be an integer from 1 to 10.
- Approve responses with a score of 7 or higher.
- If approved, revision_instructions should be empty.
- If not approved, provide specific revision instructions.
"""

        gemini_response = self.model.generate_content(review_prompt)
        response_text = gemini_response.text.strip()

        # Remove Markdown code fences if Gemini adds them
        if response_text.startswith("```"):
            response_text = (
                response_text
                .replace("```json", "")
                .replace("```", "")
                .strip()
            )

        try:
            review = json.loads(response_text)

        except json.JSONDecodeError:
            raise ValueError(
                f"Reviewer returned invalid JSON: {response_text}"
            )

        # Validate returned data
        required_fields = [
            "approved",
            "score",
            "feedback",
            "revision_instructions",
        ]

        for field in required_fields:
            if field not in review:
                raise ValueError(
                    f"Reviewer response missing field: {field}"
                )

        if not isinstance(review["approved"], bool):
            raise ValueError(
                "Reviewer field 'approved' must be boolean."
            )

        if not isinstance(review["score"], int):
            raise ValueError(
                "Reviewer field 'score' must be an integer."
            )

        if not 1 <= review["score"] <= 10:
            raise ValueError(
                "Reviewer score must be between 1 and 10."
            )

        return review